### ISSUE TITLE
Erro ao iniciar

### ISSUE THREAD

**Issue by raulikeda** [Fogelman/hybrid-cloud#1]
ubuntu@ip-172-31-95-135:~/hybrid-cloud/aws$ npm start

> aws@1.0.0 start /home/ubuntu/hybrid-cloud/aws
> node ./src/index.js

iniciando
(node:9831) UnhandledPromiseRejectionWarning: TypeError: data.Images.flatMap is not a function
    at ec2.describeImages.promise.then.data (/home/ubuntu/hybrid-cloud/aws/src/clean.js:70:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:9831) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9831) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Foi instalado:
$ apt install nodejs npm awscli
Depois foi rodado o setup e o start

**Comment by Fogelman** [comment]
Vou testar novamente
Você instalou os pacotes com “npm i” ?

**Comment by Fogelman** [comment]
@raulikeda qual é a versão de node que você está rodando?

`node -v`

**Comment by Fogelman** [comment]
Me parece que esse erro está ocorrendo já que não tem nenhuma imagem na sua conta nessa região.

**Comment by Fogelman** [comment]
Acredito que consertei o erro, já fiz o commit
